# -*- coding: utf-8 -*-
"""Data_Processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWw8ut9NeGsY8O78-zahEIAqi8xZBYj6

# Creating Dataframe
"""

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/anjalinambudiri-jpg/NFL-Sentiment-Analysis/refs/heads/Web-scraping-Function/Training%20Set%20Final.csv')

df = df[['Date','Topic/Name', 'Source', 'Link', 'Sentiment']]

df['Text'] = ""
df

#This may run as error if functions aren't previously defined
source_function_map = {
    'NFL': NFL,
    'NYP': NYP,
    'NBC': NBC,
    'BBC': BBC,
    'BD': BD,
    'NFLDD': NFLDD,
    'PFF': PFF,
    'SI': SI,
    'NBCP': NBCP,
    'ITI': ITI,
    'ATZ': ATZ,
    'LAT': LAT,
    'FD': FD,
    "NFLM": NFLM,
    'CP': CP,
    'CC': CC,
    'AXIOS' : AX,
    'AP': AP,
    'CBS' : CBS,
    'ESPN' : ESPN,
    'F13' : F13,
    'FS' : FS,
    'GE' : GE,
    'NYT' : NYT,
    'AL' : AL,
    'NTS' : NTS,
    'CLE' : CLE,
    'NBCNY' : NBCNY,
    'Sports247' : SPO247,
    'WebZone49er' : WZ,
    'NinersNation' : NN,
    'SportingNews' : SN,
    'WCVB' : WCVB,
    
}

def process_row(row):
    source = row['Source']
    # Force the Link to a string to ensure it has quotes/string properties
    link_str = str(row['Link'])

    # Check if we have a registered function for this source
    if source in source_function_map:
        run_function = source_function_map[source]
        return run_function(link_str)

    # If the source isn't in our dictionary, keep the existing Text
    return row['Text']

# Apply the processor to your dataframe
df['Text'] = df.apply(process_row, axis=1)