# -*- coding: utf-8 -*-
"""Data_Processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWw8ut9NeGsY8O78-zahEIAqi8xZBYj6

# Creating Dataframe
"""

import pandas as pd
import samplewebscraping

df = pd.read_csv('https://raw.githubusercontent.com/anjalinambudiri-jpg/NFL-Sentiment-Analysis/refs/heads/Web-scraping-Function/Training%20Set%20Final.csv')

df = df[['Date','Topic/Name', 'Source', 'Link', 'Sentiment']]

df['Text'] = ""
df

#This may run as error if functions aren't previously defined
source_function_map = {
    'NFL': samplewebscraping.NFL,
    'NYP': samplewebscraping.NYP,
    'NBC': samplewebscraping.NBC,
    'BBC': samplewebscraping.BBC,
    'BD': samplewebscraping.BD,
    'NFLDD': samplewebscraping.NFLDD,
    'PFF': samplewebscraping.PFF,
    'SI': samplewebscraping.SI,
    'NBCP': samplewebscraping.NBCP,
    'ITI': samplewebscraping.ITI,
    'ATZ': samplewebscraping.ATZ,
    'LAT': samplewebscraping.LAT,
    'FD': samplewebscraping.FD,
    "NFLM": samplewebscraping.NFLM,
    'CP': samplewebscraping.CP,
    'CC': samplewebscraping.CC,
    'AX' : samplewebscraping.AXIOS,
    'AP': samplewebscraping.AP,
    'CBS' : samplewebscraping.CBS,
    'ESPN' : samplewebscraping.ESPN,
    'F13' : samplewebscraping.F13,
    'FS' : samplewebscraping.FS,
    'GE' : samplewebscraping.GE,
    'NYT' : samplewebscraping.NYT,
    'AL' : samplewebscraping.AL,
    'NTS' : samplewebscraping.NTS,
    'CLE' : samplewebscraping.CLE,
    'NBCNY' : samplewebscraping.NBCNY,
    'SPO247' : samplewebscraping.Sports247,
    'WZ' : samplewebscraping.WebZone49er,
    'NN' : samplewebscraping.NinersNation,
    'SN' : samplewebscraping.SportingNews,
    'WCVB' : samplewebscraping.WCVB,

}

def process_row(row):
    source = row['Source']
    # Force the Link to a string to ensure it has quotes/string properties
    link_str = str(row['Link'])

    # Check if we have a registered function for this source
    if source in source_function_map:
        run_function = source_function_map[source]
        return run_function(link_str)

    # If the source isn't in our dictionary, keep the existing Text
    return row['Text']

# Apply the processor to your dataframe
df['Text'] = df.apply(process_row, axis=1)

print(df)